// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH9MRjdulWgvD9ZxkGi1lchHMujJN8fAw',
    appId: '1:44713528411:ios:54b52e10803c44c8c4c37e',
    messagingSenderId: '44713528411',
    projectId: 'civic-e7837',
    storageBucket: 'civic-e7837.firebasestorage.app',
    iosBundleId: 'com.example.civic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH9MRjdulWgvD9ZxkGi1lchHMujJN8fAw',
    appId: '1:44713528411:ios:54b52e10803c44c8c4c37e',
    messagingSenderId: '44713528411',
    projectId: 'civic-e7837',
    storageBucket: 'civic-e7837.firebasestorage.app',
    iosBundleId: 'com.example.civic',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyZhdUpa9TuyCBIA6FBMmqvOBDOoKkGAY',
    appId: '1:44713528411:web:d4d2f6d7bdbf4eb2c4c37e',
    messagingSenderId: '44713528411',
    projectId: 'civic-e7837',
    authDomain: 'civic-e7837.firebaseapp.com',
    storageBucket: 'civic-e7837.firebasestorage.app',
    measurementId: 'G-QCW9N9TMN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtHo38evKJTWlexzK1mXBObOWOdqCSS8Y',
    appId: '1:44713528411:android:5db8fac51ed1c1adc4c37e',
    messagingSenderId: '44713528411',
    projectId: 'civic-e7837',
    storageBucket: 'civic-e7837.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyZhdUpa9TuyCBIA6FBMmqvOBDOoKkGAY',
    appId: '1:44713528411:web:13ad538500621dd4c4c37e',
    messagingSenderId: '44713528411',
    projectId: 'civic-e7837',
    authDomain: 'civic-e7837.firebaseapp.com',
    storageBucket: 'civic-e7837.firebasestorage.app',
    measurementId: 'G-5RDW3ZKCJH',
  );
}
